
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class form_laundry_farrel extends javax.swing.JFrame {

    /**
     * Creates new form form_laundry_farrel
     */
    public form_laundry_farrel() {
        initComponents();
    }

    public int Total_Harga;
    
    public void reset() {
        type_input.setSelectedItem("Pilih Jenis");
        price_input.setText("");
        weight_input.setText("");
        total_input.setText("");
        cash_input.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cash_input = new javax.swing.JTextField();
        price_input = new javax.swing.JTextField();
        weight_input = new javax.swing.JTextField();
        total_input = new javax.swing.JTextField();
        type_input = new javax.swing.JComboBox<>();
        cancel_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CASH ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laundry Payment");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(":");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weight");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));
        jPanel1.add(cash_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 220, 40));
        jPanel1.add(price_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, 40));

        weight_input.setToolTipText("");
        weight_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                weight_inputKeyReleased(evt);
            }
        });
        jPanel1.add(weight_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, 40));
        jPanel1.add(total_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 220, 40));

        type_input.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Dry", "Wet", "Iron" }));
        type_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_inputActionPerformed(evt);
            }
        });
        jPanel1.add(type_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, 40));

        cancel_btn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(new javax.swing.border.SoftBevelBorder(20));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 160, 50));

        submit_btn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        submit_btn.setText("Submit");
        submit_btn.setBorder(new javax.swing.border.SoftBevelBorder(100));
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 170, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 670);

        setSize(new java.awt.Dimension(416, 708));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        if(price_input.getText().isEmpty() || weight_input.getText().isEmpty() ||
total_input.getText().isEmpty() || price_input.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Input Can't Be Empty");
        }else{
            int bayar = Integer.parseInt(cash_input.getText());
            int kembalian = bayar - Total_Harga;
            JOptionPane.showMessageDialog(null, "Kembalian Anda : \n"+kembalian );
            reset();
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void type_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_inputActionPerformed
        if(type_input.getSelectedItem().equals("Pilih Jenis")){
            price_input.setText("0");
        }else if(type_input.getSelectedItem().equals("Wet")){
            price_input.setText("3000");
        }else if(type_input.getSelectedItem().equals("Dry")){
            price_input.setText("4000");
        }else if(type_input.getSelectedItem().equals("Iron")){
            price_input.setText("5000");
        }
    }//GEN-LAST:event_type_inputActionPerformed

    private void weight_inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weight_inputKeyReleased
        if(weight_input.getText().equals("")){
            total_input.setText("0");
        }else {
            int price = Integer.parseInt(price_input.getText());
            int weight = Integer.parseInt(weight_input.getText());
            Total_Harga = price*weight;
            total_input.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_weight_inputKeyReleased

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        reset();
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_laundry_farrel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_laundry_farrel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_laundry_farrel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_laundry_farrel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_laundry_farrel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField cash_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField price_input;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField total_input;
    private javax.swing.JComboBox<String> type_input;
    private javax.swing.JTextField weight_input;
    // End of variables declaration//GEN-END:variables
}
